{% set name = "jupyter-book" %}
{% set version = "0.11.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 98bae76d879a68dd25678cc6de38ddf4c0689dfaec6a7fd6207f917277d181b7

build:
  number: 0
  entry_points:
    - jb = jupyter_book.commands:main
    - jupyter-book = jupyter_book.commands:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - docutils >=0.15,<0.17
    - jsonschema
    - jupyterbook-latex ~=0.3.1
    - jupytext >=1.8,<1.11
    - linkify-it-py ~=1.0.1
    - myst-nb ~=0.12.0
    - nbconvert <6
    - nbformat
    - pyyaml
    - sphinx >=2,<4
    - sphinx-comments
    - sphinx-copybutton
    - sphinx-external-toc ~=0.2.0
    - sphinx-panels ~=0.5.2
    - sphinx-thebe ~=0.0.8
    - sphinx_book_theme ~=0.1.0
    - sphinx_togglebutton
    - sphinxcontrib-bibtex ~=2.2.0
    - importlib_metadata;python_version <"3.7",>=3.6

test:
  imports:
    - jupyter_book
    - jupyter_book.commands
    - jupyter_book.directive
  commands:
    - pip check
    - jb --help
    - jupyter-book --help
  requires:
    - pip

about:
  home: https://executablebooks.org/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Jupyter Book: Create an online book with Jupyter Notebooks'
  dev_url: https://github.com/executablebooks/jupyter-book
  doc_url: https://jupyterbook.org

extra:
  recipe-maintainers:
    - chrisjsewell
    - moorepants
    - bollwyvl
    - AakashGfude
