{% set version = "0.11.2" %}

package:
  name: jupyter-book
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-book/jupyter-book-{{ version }}.tar.gz
  sha256: e32298e03c19f514c745062891143693c5e001a098bae9d59d2e4434b2099c54

build:
  number: 0
  entry_points:
    - jb = jupyter_book.cli.main:main
    - jupyter-book = jupyter_book.cli.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - docutils >=0.15,<0.17
    - importlib-metadata
    - jsonschema
    - jupytext >=1.8,<1.11
    - linkify-it-py ~=1.0.1
    - myst-nb ~=0.12.0
    - python >=3.6
    - pyyaml
    - sphinx >=2,<4
    - sphinx-book-theme ~=0.1.0
    - sphinx-comments
    - sphinx-copybutton
    - sphinx-external-toc ~=0.2.1
    - sphinx-panels ~=0.5.2
    - sphinx-thebe ~=0.0.8
    - sphinx-togglebutton
    - sphinxcontrib-bibtex ~=2.2.0
    - sphinx-jupyterbook-latex ~=0.4.2
    - sphinx-multitoc-numbering ~=0.1.3

test:
  imports:
    - jupyter_book
  commands:
    - pip check
    - jb --help
    - jupyter-book --help
  requires:
    - pip

about:
  home: https://executablebooks.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: |
    Jupyter Book: Create an online book with Jupyter Notebooks
  dev_url: https://github.com/executablebooks/jupyter-book
  doc_url: https://jupyterbook.org
  doc_source_url: https://github.com/executablebooks/jupyter-book/tree/v{{ version }}/docs

extra:
  recipe-maintainers:
    - chrisjsewell
    - moorepants
    - bollwyvl
    - AakashGfude
    - mmcky
