{% set version = "0.12.0" %}

package:
  name: jupyter-book
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-book/jupyter-book-{{ version }}.tar.gz
  sha256: cc0082d27239d9c1d64ac0aa2e12194cce7415cdeb498fe1c626572a2e65ea2c

build:
  number: 0
  entry_points:
    - jb = jupyter_book.cli.main:main
    - jupyter-book = jupyter_book.cli.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click >=7.1,<8
    - docutils >=0.15,<0.18
    - importlib-metadata
    - jsonschema <4
    - jupytext >=1.11.2,<1.12
    - linkify-it-py >=1.0.1,<1.1
    - myst-nb >=0.12.0,<0.13
    - python >=3.6
    - pyyaml
    - sphinx >=3,<5
    - sphinx-book-theme >=0.1.4,<0.2
    - sphinx-comments
    - sphinx-copybutton
    - sphinx-external-toc >=0.2.3,<0.3
    - sphinx-panels >=0.6.0,<0.7
    - sphinx-thebe >=0.0.10,<0.1
    - sphinx-togglebutton
    - sphinxcontrib-bibtex >=2.2.0,<2.3
    - sphinx-jupyterbook-latex >=0.4.3,<0.5
    - sphinx-multitoc-numbering >=0.1.3,<0.2

test:
  imports:
    - jupyter_book
  commands:
    - pip check
    - jb --version
    - jb --help
    - jb --version
    - jupyter-book --help
  requires:
    - pip

about:
  home: https://executablebooks.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: |
    Jupyter Book: Create an online book with Jupyter Notebooks
  dev_url: https://github.com/executablebooks/jupyter-book
  doc_url: https://jupyterbook.org
  doc_source_url: https://github.com/executablebooks/jupyter-book/tree/v{{ version }}/docs

extra:
  recipe-maintainers:
    - moorepants
    - bollwyvl
    - AakashGfude
