{% set version = "0.12.2" %}

package:
  name: jupyter-book
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-book/jupyter-book-{{ version }}.tar.gz
  sha256: 63bd18d0b05855e066498d688c57e03e47441507d07816a0cb12099d233205e8

build:
  number: 0
  entry_points:
    - jb = jupyter_book.cli.main:main
    - jupyter-book = jupyter_book.cli.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=7.1,<9
    - docutils >=0.15,<0.18
    - jsonschema <4
    - jupytext >=1.11.2,<1.12
    - linkify-it-py >=1.0.1,<1.1
    - myst-nb >=0.13.1,<0.14
    - python >=3.7
    - pyyaml
    - sphinx-book-theme >=0.1.4,<0.2.0
    - sphinx-togglebutton
    - sphinx-comments
    - sphinx-copybutton
    - sphinx-external-toc >=0.2.3,<0.3.0
    - sphinx-jupyterbook-latex >=0.4.6,<0.5.0
    - sphinx-multitoc-numbering >=0.1.3,<0.2.0
    - sphinx-panels >=0.6.0,<0.7.0
    - sphinx-thebe >=0.1.1,<0.2.0
    - sphinx >=3,<5
    - sphinxcontrib-bibtex >=2.2.0,<2.5.0

test:
  imports:
    - jupyter_book
  commands:
    - pip check
    - jb --version
    - jb --help
    - jupyter-book --version
    - jupyter-book --help
  requires:
    - pip

about:
  home: https://executablebooks.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: |
    Jupyter Book: Create an online book with Jupyter Notebooks
  dev_url: https://github.com/executablebooks/jupyter-book
  doc_url: https://jupyterbook.org
  doc_source_url: https://github.com/executablebooks/jupyter-book/tree/v{{ version }}/docs

extra:
  recipe-maintainers:
    - moorepants
    - bollwyvl
    - AakashGfude
